ControledeContatos/Models/ContatoModel.cs
namespace ControledeContatos.Models
{
    public class ContatoModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Celular { get; set; }
    }
}

ControledeContatos/Models/ErrorViewModel.cs
namespace ControledeContatos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ControledeContatos/Models/ObjetoModel.cs
namespace ControledeContatos.Models
{
    public class ObjetoModel
    {
        private string detalhes;

        public int Id { get; set; }
        public string Objeto { get; set; }
        public string Modelo { get; set; }
        public string Detalhes { get => detalhes; set => detalhes = value; }
        public string Localizacao { get; set; }
    }
}

ControledeContatos/Controllers/ContatoController.cs
using ControledeContatos.Models;
using Microsoft.AspNetCore.Mvc;

namespace ControledeContatos.Controllers
{
    public class ContatoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Criar()
        {
            return View();
        }
        public IActionResult Editar()
        {
            return View();
        }
        public IActionResult Excluir()
        {
            return View();
        }
      //  [HttpPost]

        // public IActionResult Criar(ContatoModel contato)

     


    }
}

ControledeContatos/Controllers/HomeController.cs
using ControledeContatos.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ControledeContatos.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ControledeContatos/Views/Contato/Criar.cshtml
@{
    ViewData["Title"] = "Cadastro de Usuário";
}
<div class="text-center">
    <h1 class="display-4">Cadastro de Usuário</h1>
</div>
<br />

<form>
    <div class="form-group">
        <label for="Nome">Nome Completo</label>
        <input type="text" class="form-control" placeholder="Digite o seu Nome Completo">
    </div>
    <div class="form-group">
        <label for="Email">E-mail</label>
        <input type="text" class="form-control" placeholder="Digite o seu melhor E-mail">
    </div>
    <div class="form-group">
        <label for="Phone">Telefone</label>
        <input type="text" class="form-control" placeholder="Digite o Número do seu  Telefone">
    </div>
    <p></p>
    <p></p>
    <label for="data_nascimento">Data de Nascimento</label>
    <input type="date" name="data_nascimento" id="data_nascimento" required>
    <br />
    <br>
    <p>Sexo:</p>
    <input type="radio" name="genero" value="feminino" required>
    <label for="feminino">Feminino</label>
    <input type="radio" name="genero" value="masculino" required>
    <label for="masculino">Masculino</label>
    <input type="radio" name="genero" value="outro" required>
    <label for="outro">Outro</label>
    <br>
    <br>
    
    <div class="row">
        <div class="inputbox">
            <label for="cep">CEP:</label>
            <input type="text" id="cep"  required>


            <div class="inputbox">
                <label for="endereco">Endereço</label>
                <input type="text" id="endereco" class="form-control" placeholder="Digite o seu Endereço">
                
            </div>

            <div class="inputbox">
                <label for="numero">Número</label>
                <input type="text" id="numero" class="form-control" placeholder="Digite o Número da Casa ou Apto">
            </div>

            <div class="inputbox">
                <label for="bairro">Bairro</label>
                <input type="text" id="bairro" class="form-control" placeholder="Digite o Nome do Bairro">
            </div>

            <div class="inputbox">
                <label for="cidade">Cidade</label>
                <input type="text" id="cidade" class="form-control" placeholder="Digite o Nome da Cidade">
            </div>

            <div class="inputbox">
                <label for="estado">Estado</label>
                <input type="text" id="estado" class="form-control" placeholder="Digite o Nome do Estado">
            </div>

    <p></p>
    <p></p>
    <button type="submit" class="btn btn-primary btn-toolbar"> Adicionar</button>
    <br />
    <a class="btn btn-secondary" asp-controller="Contato" asp-action="Index" role="button">Voltar</a>
</form> 

<br />
/*add busca por CEP - FINALIZADA EM 19/9/22
Motivo de ter Sexo e Endereço: para que a Equipe de Logóstica possa validar se o Usuário que está retirando o OBJETO é o mesmo Usuário Cadastrado*/

ControledeContatos/Views/Contato/CriarObjeto.cshtml
@{
    ViewData["Title"] ="Cadastro de Achados & Perdidos";
}
<div class="text-center"><h1 class="display-4">Cadastro de Achados & Perdidos</h1></div>
<br />

<form>
    <div class="form-group">
        <label for="Objeto">O que você Encontrou / Perdeu?</label>
        <input type="text" class="form-control" placeholder="O que você perdeu / Encontrou?">
    </div>
    <div class="form-group">
        <label for="Modelo">Modelo</label>
        <input type="text" class="form-control" placeholder="Qual a Marca / Modelo?">
    </div>
    <div class="form-group">
        <label for="Detalhes">Detalhes</label>
        <input type="text" class="form-control" placeholder="Quais os detalhes?">
    </div>
    <div class="form-group">
        <label for="Localizacao">Localizacao</label>
        <input type="text" class="form-control" placeholder="Onde você encontrou / perdeu?">
    </div>
    <p></p>
    <button type="submit" class="btn btn-primary btn-toolbar"> Adicionar Achados & Perdidos</button>
    <br />
    <a class="btn btn-primary btn-toolbar" asp-controller="Contato" asp-action="Index" role="button">Voltar</a>
</form>

ControledeContatos/Views/Contato/Editar.cshtml
@{
    ViewData["Title"] = "Editar Contato";
}
<div class="text-center"><h1 class="display-4">Editar Contato</h1></div>
<br />

<form>
    <div class="form-group">
        <label for="Nome">Nome Completo</label>
        <input type="text" class="form-control" placeholder="Digite o seu Nome Completo">
    </div>
    <div class="form-group">
        <label for="Email">E-mail</label>
        <input type="text" class="form-control" placeholder="Digite o seu melhor E-mail">
    </div>
    <div class="form-group">
        <label for="Phone">Telefone</label>
        <input type="text" class="form-control" placeholder="Digite o Número do seu  Telefone">
    </div>
    <p></p>
    <p></p>

    <label for="data_nascimento">Data de Nascimento</label>
    <input type="date" name="data_nascimento" id="data_nascimento" required>
    <br />
    <br>
    <p>Sexo:</p>
    <input type="radio" name="genero" value="feminino" required>
    <label for="feminino">Feminino</label>
    <input type="radio" name="genero" value="masculino" required>
    <label for="masculino">Masculino</label>
    <input type="radio" name="genero" value="outro" required>
    <label for="outro">Outro</label>
    <br>
    <br>
    <div class="form-group">
        <label for="Phone">Endereço</label>
        <input type="text" class="form-control" placeholder="Digite o seu Endereço">
    </div>
    <div class="form-group">
        <label for="Phone">Cidade</label>
        <input type="text" class="form-control" placeholder="Digite o Nome da sua Cidade">
    </div>
    <div class="form-group">
        <label for="Phone">Estado</label>
        <input type="text" class="form-control" placeholder="Digite a Sigla do seu Estado">
    </div>
    <br />

    <button type="submit" class="btn btn-primary btn-toolbar">Editar Contato</button>
    <br />
    <a class="btn btn-secondary btn-block" asp-controller="Contato" asp-action="Index" role="button">Voltar</a>
</form>

ControledeContatos/Views/Contato/Excluir.cshtml
@{
    ViewData["Title"] = "Excluir Contato";
}
<div class="text-center"><h1 class="display-4">Excluir Contato</h1></div>
<br />

<div class="text-center">
    <h3> Realmente deseja excluir o Contato?</h3>
</div> 
<br />
<div class="text-center">
<a class="btn btn-primary" asp-controller="Contato" asp-action="Index" role="button">Cancelar</a>
<br/>
<br/>
<a class="btn btn-danger" asp-controller="Contato" asp-action="Apagar" role="button">Confirmar</a>
</div>





//suze: preciso terminar esse item

ControledeContatos/Views/Contato/Index.cshtml
@{
    ViewData["Title"] = "Lista de Usuários";
}
<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Contato" asp-action="Criar">Adicionar Novo Usuário</a>
    </div>
    <br />
    <h1 class="display-4">Lista de Usuários</h1>
    

     <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">E-mail</th>
                <th scope="col">Telefone</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1</th>
                <td>João</td>
                <td>joao@senac.com</td>
                <td>(47) 99183-3888</td>
                <td>
                    <div class="btn-group" role="group">
                        <a role="button " class="btn btn-primary" asp-controller="Contato" asp-action="Editar">Editar</a>
                        <a role="button " class="btn btn-danger" asp-controller="Contato" asp-action="Excluir">Excluir</a>
                    </div>
                </td>
            </tr>
            <tr>
                <th scope="row">2</th>
                <td>Maria</td>
                <td>mariadocarmo@senac.com</td>
                <td>(47) 99183-3889</td>
                <td>
                    <div class="btn-group" role="group">
                        <a role="button " class="btn btn-primary" asp-controller="Contato" asp-action="Editar">Editar</a>
                        <a role="button " class="btn btn-danger" asp-controller="Contato" asp-action="Excluir">Excluir</a>
                    </div>
                </td>
            </tr>
            <tr>
                <th scope="row">3</th>
                <td>Paulo</td>
                <td>paulo@senac.com</td>
                <td>(47) 99183-3885</td>
                <td>
                    <div class="btn-group" role="group">
                        <a role="button " class="btn btn-primary" asp-controller="Contato" asp-action="Editar">Editar</a>
                        <a role="button " class="btn btn-danger" asp-controller="Contato" asp-action="Excluir">Excluir</a>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
</div>

ControledeContatos/Views/Home/Adicionais.cshtml
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="..." alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="..." alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="..." alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<div class="carousel-item">
    <img src="..." alt="...">
    <div class="carousel-caption d-none d-md-block">
        <h5>...</h5>
        <p>...</p>
    </div>
</div>




<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

ControledeContatos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página Inicial";
}

<div class="text-center">
    <h1 class="display-4">Bem-Vindo!</h1>
    <p>
        Sistema de Achados & Perdidos
    </p>
</div>

ControledeContatos/Views/Objeto/Editar.cshtml
@{
    ViewData["Title"] = "Editar Cadastro de Achados & Perdidos";
}
<div class="text-center"><h1 class="display-4">Editar Cadastro de Achados & Perdidos</h1></div>
<br />

<form>
    <div class="form-group">
        <label for="Objeto">O que você Encontrou / Perdeu?</label>
        <input type="text" class="form-control" placeholder="O que você perdeu / Encontrou?">
    </div>
    <div class="form-group">
        <label for="Modelo">Modelo</label>
        <input type="text" class="form-control" placeholder="Qual a Marca / Modelo?">
    </div>
    <div class="form-group">
        <label for="Detalhes">Detalhes</label>
        <input type="text" class="form-control" placeholder="Quais os detalhes?">
    </div>
    <div class="form-group">
        <label for="Localizacao">Localizacao</label>
        <input type="text" class="form-control" placeholder="Onde você encontrou / perdeu?">
    </div>
        <br />

    <button type="submit" class="btn btn-primary btn-toolbar"> Editar Cadastro de Achados & Perdidos</button>
    <br />
    <a class="btn btn-primary btn-block" asp-controller="Contato" asp-action="Index" role="button">Voltar</a>
</form>

ControledeContatos/Views/Objeto/Excluir.cshtml
@{
    ViewData["Title"] = "Excluir Contato";
}
<div class="text-center"><h1 class="display-4">Excluir Achados & Perdidos</h1></div>
<br />

<div class="text-center">
    <h3> Realmente deseja excluir o Item?</h3>
</div>
<br />
<a class="btn btn-primary btn-toolbar" asp-controller="Contato" asp-action="Editar" role="button">Cancelar</a>
<br />
<a class="btn btn-primary btn-toolbar" asp-controller="Contato" asp-action="Apagar" role="button">Confirmar</a>

ControledeContatos/Views/Objeto/Index.cshtml
@{
    ViewData["Title"] = "Lista de Objetos";
}
<div class="text-center"><h1 class="display-4">Lista de Objetos</h1></div>
<br />

<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Contato" asp-action="Criar"> Adicionar Novo Objeto</a>
    </div>

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Objeto</th>
                <th scope="col">Modelo</th>
                <th scope="col">Descriçãoe</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1</th>
                <td>Celular</td>
                <td>Motorola G4 Play</td>
                <td>Celular com azul escuro com capa transparente</td>
                <td>
                    <div class="btn-group" role="group">
                        <a role="button " class="btn btn-primary" asp-controller="Contato" asp-action="Editar">Editar</a>
                        <a role="button " class="btn btn-primary" asp-controller="Contato" asp-action="Excluir">Excluir</a>
                    </div>
                </td>
            </tr>
            <tr>
                <th scope="row">2</th>
                <td>Jacob</td>
                <td>thorton@gmail.com</td>
                <td>47 9 9183 3889</td>
                <td>
                    <div class="btn-group" role="group">
                        <a role="button " class="btn btn-primary" asp-controller="Contato" asp-action="Editar">Editar</a>
                        <a role="button " class="btn btn-primary" asp-controller="Contato" asp-action="Excluir">Excluir</a>
                    </div>
                </td>
            </tr>
            <tr>
                <th scope="row">3</th>
                <td>Larry</td>
                <td>thebird@gmail.com</td>
                <td>47 9 9183 3885</td>
                <td>
                    <div class="btn-group" role="group">
                        <a role="button " class="btn btn-primary" asp-controller="Contato" asp-action="Editar">Editar</a>
                        <a role="button " class="btn btn-primary" asp-controller="Contato" asp-action="Excluir">Excluir</a>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
</div>

ControledeContatos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Achados & Perdidos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ControledeContatos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" btn-primary asp-area="" asp-controller="Home" asp-action="Index">Achados & Perdidos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contato" asp-action="Index">Usuário</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contatos" asp-action="CriarObjeto">Achados & Perdidos</a>
                        </li>
                        <li class="nav-item">
                            <a href="Index3.cshtml"> Perdidos</a>
                            
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Achados e Perdidos
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>